### PR TITLE
Add new interested parties

### PR DESCRIPTION
**Pull request by diegosiqueir4**
This commit includes people who commented on the issue #1 after Franziska Klemstein ([last added](4419320b94ac361e756a457a43fce7dff3276496))

### CODE REVIEW

**Comment by fbkarsdorp** [comment]
That's great! Thanks. I was too lazy to add a JS function to sort the list by last names, so we have to manually add the names to the correct places. Would you mind doing that?

**Comment by diegosiqueir4** [comment]
> That's great! Thanks. I was too lazy to add a JS function to sort the list by last names, so we have to manually add the names to the correct places. Would you mind doing that?

sure, no problem :)

**Comment by fbkarsdorp** [comment]
Great. Thanks.

**Comment by diegosiqueir4** [comment]
> Great. Thanks.

I am happy to contribute :) Thanks for taking the time to review it.

**Pull request merged**
